#include "stdafx.h"
#include "VertexLayouts.h"

#define VERTEX_RG				DXGI_FORMAT_R32G32_FLOAT
#define VERTEX_RGB				DXGI_FORMAT_R32G32B32_FLOAT
#define VERTEX_RGBA				DXGI_FORMAT_R32G32B32A32_FLOAT
#define VERTEX					D3D11_INPUT_PER_VERTEX_DATA

#define ALIGNED_ELEMENT			D3D11_APPEND_ALIGNED_ELEMENT

D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_POSITION = { "POSITION", 0, VERTEX_RGB, 0, 0,    VERTEX, 0 };
D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_COLOR = { "COLOR", 0, VERTEX_RGBA, 0, ALIGNED_ELEMENT, VERTEX, 0 };
D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_TEXCOORD = { "TEXCOORD", 0, VERTEX_RG, 0, ALIGNED_ELEMENT, VERTEX, 0 };
D3D11_INPUT_ELEMENT_DESC  INPUT_ELEMENT_PARAMETER_NORMAL = { "NORMAL", 0, VERTEX_RGB, 0, ALIGNED_ELEMENT, VERTEX, 0 };

//=======================================================================================

D3D11_INPUT_ELEMENT_DESC Vertex::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
};

D3D11_INPUT_ELEMENT_DESC VertexColor::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_COLOR,
};

D3D11_INPUT_ELEMENT_DESC VertexColorNormal::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_COLOR,
	INPUT_ELEMENT_PARAMETER_NORMAL
};

D3D11_INPUT_ELEMENT_DESC VertexTexture::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_TEXCOORD,
};

D3D11_INPUT_ELEMENT_DESC VertexTextureNormal::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_TEXCOORD,
	INPUT_ELEMENT_PARAMETER_NORMAL,
};

D3D11_INPUT_ELEMENT_DESC VertexColorTextureNormal::desc[] =
{
	INPUT_ELEMENT_PARAMETER_POSITION,
	INPUT_ELEMENT_PARAMETER_COLOR,
	INPUT_ELEMENT_PARAMETER_TEXCOORD,
	INPUT_ELEMENT_PARAMETER_NORMAL,
};

//=======================================================================================

UINT Vertex::count = 1;
UINT VertexColor::count = 2;
UINT VertexColorNormal::count = 3;
UINT VertexTexture::count = 2;
UINT VertexTextureNormal::count = 3;
UINT VertexColorTextureNormal::count = 4;
